---
- name: Create a pretalx user
  user:
    name: "{{ pretalx_system_user }}"
    state: present
  tags:
    - pretalx

- name: Create required directories
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ pretalx_system_user }}"
    recurse: yes
  with_items:
    - "{{ pretalx_staticfiles_directory }}"
    - "{{ pretalx_data_dir }}"
    - "{{ pretalx_media_dir }}"
  tags:
    - pretalx

- name: Install redis client
  pip:
    name: django_redis
    executable: pip3
    extra_args: --user
    state: latest
  become: true
  become_user: "{{ pretalx_system_user }}"
  when: pretalx_redis is defined
  tags:
    - pretalx

- name: Configure pretalx
  template:
    src: pretalx.cfg.j2
    dest: ~/.pretalx.cfg
  notify:
    - Restart pretalx service
    - Run pretalx migrations
    - Collect static pretalx files
    - Compress static pretalx files
    - Compile pretalx messages
  become: true
  become_user: "{{ pretalx_system_user }}"
  tags:
    - pretalx
    - pretalxupdate

- name: Install pretalx (latest)
  pip:
    name: pretalx
    executable: pip3
    extra_args: --user
    state: latest
  notify:
    - Restart pretalx service
    - Run pretalx migrations
    - Collect static pretalx files
    - Compress static pretalx files
    - Compile pretalx messages
  when: (pretalx_version == 'latest') and not (pretalx_git_version)
  become: true
  become_user: "{{ pretalx_system_user }}"
  tags:
    - pretalx
    - pretalxupdate

- name: Install pretalx (versioned)
  pip:
    name: pretalx
    executable: pip3
    extra_args: --user
    version: "{{ pretalx_version }}"
  notify:
    - Restart pretalx service
    - Run pretalx migrations
    - Collect static pretalx files
    - Compress static pretalx files
    - Compile pretalx messages
  when: (pretalx_version != 'latest') and not pretalx_git_version
  become: true
  become_user: "{{ pretalx_system_user }}"
  tags:
    - pretalx
    - pretalxupdate

- name: Install pretalx (git)
  pip:
    name: git+git://github.com/pretalx/pretalx.git@{{ pretalx_git_version }}#egg=pretalx&subdirectory=src
    executable: pip3
    extra_args: --user
    state: latest
  notify:
    - Restart pretalx service
    - Run pretalx migrations
    - Collect static pretalx files
    - Compress static pretalx files
    - Compile pretalx messages
  when: (pretalx_git_version != "")
  become: true
  become_user: "{{ pretalx_system_user }}"
  changed_when: true
  tags:
    - pretalx
    - pretalxupdate

- name: Make sure plugin directory exists
  file:
    path: ~{{ pretalx_system_user }}/plugins
    state: directory
    owner: "{{ pretalx_system_user }}"
    recurse: true
  when: pretalx_plugins
  tags:
    - pretalx
    - pretalxupdate

- name: Install pretalx plugins
  git:
    repo: "{{ item.repository }}"
    dest: ~{{ pretalx_system_user }}/plugins/{{ item.name }}
    version: master
    key_file: ~{{ pretalx_system_user }}/.ssh/id_rsa
    accept_hostkey: yes
  become: true
  become_user: "{{ pretalx_system_user }}"
  with_items: "{{ pretalx_plugins }}"
  when: pretalx_plugins
  notify:
    - Restart pretalx service
    - Run pretalx migrations
    - Collect static pretalx files
    - Compress static pretalx files
    - Compile pretalx messages
    - Install pretalx plugins
  tags:
    - pretalx
    - pretalxupdate

- name: Install systemd socket
  template:
    src: pretalx.socket.j2
    dest: /etc/systemd/system/pretalx@.socket
  notify:
    - Reload systemd services
    - Restart pretalx socket
  tags:
    - pretalx

- name: Install systemd service
  template:
    src: pretalx.service.j2
    dest: /etc/systemd/system/pretalx@.service
  notify:
    - Reload systemd services
    - Restart pretalx service
  tags:
    - pretalx

- name: Install worker service
  template:
    src: pretalx-worker.service.j2
    dest: /etc/systemd/system/pretalx-worker@.service
  notify:
    - Reload systemd services
    - Restart worker service
  tags:
    - pretalx

- name: Start pretalx socket
  service:
    name: pretalx@{{ pretalx_instance_identifier }}.socket
    state: started
    enabled: true
  tags:
    - pretalx

- name: Start systemd service
  service:
    name: pretalx@{{ pretalx_instance_identifier }}
    state: started
    enabled: true
  tags:
    - pretalx

- name: Start worker service
  service:
    name: pretalx-worker@{{ pretalx_instance_identifier }}
    state: started
    enabled: true
  tags:
    - pretalx

- name: Configure nginx
  template:
    src: nginx.conf
    dest: "{{ pretalx_nginx_path }}/pretalx_{{ pretalx_instance_identifier }}.conf"
  when: pretalx_nginx is defined and pretalx_nginx
  notify:
    - Reload nginx
  tags:
    - pretalx
